### ISSUE TITLE
Reduce data copy

### ISSUE THREAD

**Issue by tathanhdinh** [tandasat/UefiVarMonitor#1]
Hello,

IMHO, we may reduce some data copy in `let mut var_name_buffer = [0; 64];`

https://github.com/tandasat/UefiVarMonitor/blob/788440aa9c5058e6f1e894a83d736b4af713039f/uefi-var-monitor/src/main.rs#L36-L50

using `mem::MaybeUninit`

```rust
let mut name;
let name = unsafe {
    let variable_name = core::slice::from_raw_parts(variable_name, 64);
    name = core::mem::MaybeUninit::<[u8; 64]>::uninit();
    let name_ptr = name.as_mut_ptr() as *mut u8;
    let mut offset = 0;
    for c in variable_name.iter().take_while(|&&c| c != 0).map(|&c| c as u8)  {
        name_ptr.add(offset).write(c);
        offset = offset + 1;
    }
    core::str::from_utf8_unchecked(core::slice::from_raw_parts(name_ptr, offset))
};
```

**Comment by tandasat** [comment]
Thanks for suggestion with a functional code snippet! I replaced the implementation with this (and learned more things about Rust 👍 )
